# Generated by Django 6.1.1 on 2026-09-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tittle',
            new_name='title',
        ),
    ]
